# Generated by Django 3.2.7 on 2022-03-28 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassContentAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artClass', models.CharField(max_length=64, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='FriendApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(max_length=64, verbose_name='申请人的Id')),
                ('friendsId', models.IntegerField(max_length=64, verbose_name='被申请人的Id')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建账号日期')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('level', models.IntegerField(default='1', verbose_name='管理员等级')),
                ('nickname', models.CharField(default='user', max_length=64, verbose_name='用户昵称')),
                ('status', models.IntegerField(default=0, max_length=64, verbose_name='用户状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserFriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(max_length=64, verbose_name='用户的ID')),
                ('friendsId', models.IntegerField(max_length=64, verbose_name='对应的好友ID')),
                ('groupName', models.CharField(max_length=254, verbose_name='好友频道名')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='用户token')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='book.user')),
            ],
        ),
    ]
