# Generated by Django 4.0.2 on 2022-02-06 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='用户名', max_length=64, verbose_name='用户名'),
        ),
    ]
