# Generated by Django 3.2.7 on 2022-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendapply',
            name='applyStatus',
            field=models.IntegerField(default=0, max_length=64, verbose_name='申请状态'),
            preserve_default=False,
        ),
    ]
