# Generated by Django 3.2.7 on 2022-03-15 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user_nickname_alter_user_username_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(max_length=64, verbose_name='用户的ID')),
                ('friendsId', models.IntegerField(max_length=64, verbose_name='对应的好友ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='editioncontent',
            name='editionType',
        ),
        migrations.RemoveField(
            model_name='fangteacherclass',
            name='classContent',
        ),
        migrations.DeleteModel(
            name='edition',
        ),
        migrations.DeleteModel(
            name='editionContent',
        ),
        migrations.DeleteModel(
            name='FangTeacherClass',
        ),
    ]
