# Generated by Django 3.2.7 on 2022-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_friendapply_applystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChagMsgData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(max_length=64, verbose_name='发送消息的用户的ID')),
                ('msg', models.CharField(max_length=254, verbose_name='聊天的内容')),
                ('getGroupName', models.IntegerField(max_length=64, verbose_name='聊天组Id')),
            ],
        ),
    ]
