# Generated by Django 3.2.7 on 2022-03-15 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220315_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendlist',
            name='userInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.user'),
            preserve_default=False,
        ),

    ]
