# Generated by Django 3.2.7 on 2022-04-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_chagmsgdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChagMsgData',
            new_name='ChatMsgData',
        ),
    ]
