# Generated by Django 3.2.7 on 2022-04-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_chagmsgdata_chatmsgdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmsgdata',
            old_name='getGroupName',
            new_name='groupName',
        ),
    ]
