# Generated by Django 3.2.7 on 2022-03-15 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220315_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriendlist',
            name='userInfo',
        ),

    ]
