# Generated by Django 3.2.7 on 2022-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_getgroupname_chatmsgdata_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmsgdata',
            name='groupName',
            field=models.CharField(max_length=64, verbose_name='聊天组Id'),
        ),
    ]
