# Generated by Django 3.2.7 on 2022-04-03 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_chatmsgdata_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmsgdata',
            name='msgTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
