# Generated by Django 3.2.7 on 2022-03-17 15:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220315_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, max_length=64, verbose_name='用户在线离线状态'),
        ),
    ]
