# Generated by Django 3.2.7 on 2022-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_chatmsgdata_msgtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headicon',
            field=models.ImageField(default=0, upload_to='headIcon/'),
            preserve_default=False,
        ),
    ]
