# Generated by Django 3.2.7 on 2022-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_user_headicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headicon',
            field=models.CharField(default=None, max_length=254, verbose_name='图片的url地址'),
        ),
    ]
