# Generated by Django 3.2.7 on 2022-03-19 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20220318_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriendlist',
            name='User',
        ),

    ]
