# Generated by Django 3.2.7 on 2022-04-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_user_headicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
